project_name: 'hpp_azero_curriculum'
max_episodes: -1
eval_period_episodes: 5000
full_evaluation_period: 20
load_checkpoint: 'az_295000_1_0.43_1y4hhusv.pt'
checkpoint_path: './checkpoints'
start_level: 0
end_level: 80
success_rate_next_level: 0.5
change_level_every: 50000
levels_at_once: 5
maps: null
optimize_every_step: 512

agent:
  batch_size: 512
  gamma: 0.95
  eps_start: 0.1
  eps_end: 0.001
  eps_decay: 10000
  n_actions: 8
  n_layers: 1
  input_vector_size: 2
  capacity: 2000000
  learning_rate: 0.00001

environment:
  window_size: 11
  goal_reward: 0
  distance_reward_weight_forward: 0
  distance_reward_weight_backward: 0
  rest_distance_reward_weight: 0
  collision_reward: 0
  move_reward: 0
  max_steps_mult: 3
  path: ../../dataset/256/