project_name: 'hpp_azero_curriculum'
max_epoch: -1
eval_period_epoch: 2500
load_checkpoint: null
checkpoint_path: './checkpoints'
min_level: 0
max_level: 80
success_rate_next_level: 0.5
sample_every: 10000
sample_size: 35
maps: null

agent:
  batch_size: 1024
  gamma: 0.95
  eps_start: 0.1
  eps_end: 0.001
  eps_decay: 10000
  n_actions: 8
  n_layers: 1
  input_vector_size: 2
  capacity: 1000000
  learning_rate: 0.00001

environment:
  window_size: 21
  goal_reward: 0
  distance_reward_weight_forward: 0
  distance_reward_weight_backward: 0
  rest_distance_reward_weight: 0
  collision_reward: 0
  move_reward: 0
  max_steps_mult: 3
  path: ../../dataset/256/