project_name: 'hpp_vp_net_curriculum'
max_episodes: -1
eval_period_episodes: 10000
full_evaluation_period: 5
load_checkpoint: null
checkpoint_path: './checkpoints'
start_level: 0
end_level: 25
success_rate_next_level: 0.5
change_level_every: 100000
levels_at_once: 5
maps: null
optimize_every_step: 1024

agent:
  batch_size: 1000
  gamma: 0.95
  eps_start: 0.2
  eps_end: 0.01
  eps_decay: 10000
  n_actions: 8
  n_layers: 1
  input_vector_size: 2
  capacity: 1000000
  learning_rate: 0.00001

environment:
  window_size: 21
  goal_reward: 0
  distance_reward_weight_forward: 0
  distance_reward_weight_backward: 0
  rest_distance_reward_weight: 0
  collision_reward: 0
  move_reward: 0
  max_steps_mult: 3
  path: ../../dataset/256/
  disable_repetitions: true